#! /bin/bash
set $mod Mod4
font pango:monospace 8
exec --no-startup-id "setxkbmap -layout gb"
exec --no-startup-id "setxkbmap -option caps:escape"
exec --no-startup-id "xmodmap -e 'keycode 108 = Super_R'"
exec --no-startup-id "xset -r 108"
exec --no-startup-id "dunst"
exec --no-startup-id "sleep 1; setxkbmap -layout gb; setxkbmap -option caps:escape"

floating_modifier $mod
for_window [class="Termite"] border pixel 10
# for_window [class=.] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [class="VirtualBox Machine"] fullscreen enable
for_window [class="VirtualBox Machine"] move container to workspace $ws9
for_window [class="Kodi"] floating enable
default_border none
focus_follows_mouse yes
gaps inner 10
gaps outer 0
smart_gaps on

bindsym $mod+Return exec --no-startup-id "termite"
bindsym $mod+Shift+Return exec --no-startup-id "qutebrowser"
bindsym $mod+o exec --no-startup-id "rofi -show run -display-run '>>> ' -width 400 -theme ~/.config/rofi/bala.rasi"
bindsym $mod+space exec --no-startup-id "rofi -show run -display-run '>>> ' -width 400 -theme ~/.config/rofi/bala.rasi"
bindsym $mod+Shift+o exec --no-startup-id "rofi -width 400 -show window -display-window '$$$ ' -theme ~/.config/rofi/bala.rasi"
bindsym $mod+Shift+space exec --no-startup-id "rofi -width 400 -show window -display-window '$$$ ' -theme ~/.config/rofi/bala.rasi"
bindsym $mod+F3 exec --no-startup-id "pactl set-sink-volume 0 +5%"
bindsym $mod+F2 exec --no-startup-id "pactl set-sink-volume 0 -5%"
# bindsym XF86AudioRaiseVolume exec --no-startup-id "pactl set-sink-volume 0 +5%"
# bindsym $XF86AudioLowerVolume exec --no-startup-id "pactl set-sink-volume 0 -5%"
bindsym $mod+equal exec "pactl set-sink-volume 0 +5%"
bindsym $mod+minus exec "pactl set-sink-volume 0 -5%"
bindsym $mod+0 exec --no-startup-id "pactl set-sink-mute 0 toggle"
bindsym $mod+F1 exec --no-startup-id "pactl set-sink-mute 0 toggle"
bindsym $mod+F12 exec --no-startup-id "xbacklight -inc 5"
bindsym $mod+F11 exec --no-startup-id "xbacklight -dec 5"

bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Left workspace prev
bindsym $mod+Down workspace next_on_output
bindsym $mod+Up workspace prev_on_output
bindsym $mod+Right workspace next
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

bindsym $mod+Shift+bar split h
bindsym $mod+v split v
bindsym $mod+g split h
bindsym $mod+f fullscreen toggle
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+d floating toggle
bindsym $mod+Shift+d focus mode_toggle
bindsym $mod+a focus parent
bindsym $mod+z focus child
bindsym $mod+Shift+m move scratchpad
bindsym $mod+m scratchpad show
bindsym $mod+n sticky toggle
bindsym $mod+q kill

set $ws1 "1:  "
set $ws2 "2:  "
set $ws3 "3:  "
set $ws4 "4:  "
set $ws5 "5:  "
set $ws6 "6:  "
set $ws7 "7:  "
set $ws8 "8:  "
set $ws9 "9:  "

bindsym $mod+t exec --no-startup-id i3-input -F 'workspace "%s"' -P ''
bindsym $mod+Shift+t exec --no-startup-id i3-input -F 'move container to workspace "%s"' -P ''

bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9

bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9

bindsym --release $mod+x exec --no-startup-id scrot -s ~/Media/Screenshots/%Y-%m-%d-%H%M%S.png
# bindsym $mod+Ctrl+l exec --no-startup-id "scrot ~/Media/blur.png && convert ~/Media/blur.png -blur 0x8 ~/Media/blur.png && i3lock -etu -p default -i ~/Media/blur.png -n && rm ~/Media/blur.png"
bindsym $mod+Ctrl+l exec --no-startup-id "i3lock -etu -p default -c '#111111'"
bindsym $mod+F9 exec --no-startup-id "scrot ~/Media/blur.png && convert ~/Media/blur.png -blur 0x8 ~/Media/blur.png && i3lock -etu -p default -i ~/Media/blur.png -n && rm ~/Media/blur.png"
bindsym $mod+p exec playerctl play-pause
bindsym $mod+bracketleft exec playerctl previous
bindsym $mod+bracketright exec playerctl next

bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
# bindsym $mod+Shift+e exec "i3-msg exit"
bindsym $mod+r mode "resize"

mode "resize" {
        bindsym h resize shrink width 10 px or 1 ppt
        bindsym j resize grow height 10 px or 1 ppt
        bindsym k resize shrink height 10 px or 1 ppt
        bindsym l resize grow width 10 px or 1 ppt
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

client.focused          #191919 #191919 #cccccc #191919   #191919
client.focused_inactive #191919 #191919 #555555 #191919   #191919
client.unfocused        #191919 #191919 #555555 #191919   #191919
client.urgent           #191919 #191919 #555555 #191919   #191919
client.placeholder      #191919 #191919 #555555 #191919   #191919

bindsym $mod+b bar mode toggle
bar {
	status_command i3status
	modifier Mod1
	position bottom
	# mode hide
	strip_workspace_numbers yes
	colors {
		background #222222
		statusline #bbbbbb
		active_workspace #222222 #222222 #bbbbbb
		focused_workspace #222222 #000000 #bbbbbb
		urgent_workspace #666666 #666666 #bbbbbb
	}
}

bindsym --release $mod+Ctrl+1 exec --no-startup-id goto1
bindsym --release $mod+Ctrl+2 exec --no-startup-id goto2
bindsym --release $mod+Ctrl+3 exec --no-startup-id goto3
